# This is hardrolled to make things easier—we expect to be able to be a bit more dynamic soon!
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: production
data:
  PORT: "3000"
  LOGGING_URL: "http://loki:3100/loki/api/v1/push"
  PROMETHEUS_URL: "http://prometheus:9090"
  REDIS_URL: "redis://redis:6379"
  SAML_CERT_PATH: "/certs/saml_cert.cert"
  SAML_KEY_PATH: "/certs/saml_key.key"
  IDP_URL: "https://idp.elon.edu/idp/shibboleth"
  SP_URL: "https://ods.elon.edu"




