loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1
  storage:
    type: "filesystem"
  ingester:
    lifecycler:
      address: 127.0.0.1
      ring:
        kvstore:
          store: inmemory
        replication_factor: 1
      final_sleep: 0s
    chunk_idle_period: 5m
    chunk_retain_period: 30s

  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h

singleBinary:
  replicas: 1
