openapi: 3.0.0
info:
  title: Buildings API
  description: "This API returns building information for Elon University."
  version: 1.0.0
  contact:
    email: api@elonsoc.org

# Define servers on which this API can be accessed
servers:
  - url: https://api.elon.edu/locations/v1/buildings
  - url: http://localhost:1337/locations/v1/buildings

# Define tags to group related endpoints
tags:
  - name: building
    description: Information on the Buildings on Campus

# Define endpoints that this API supports
paths:
  # Endpoint to get specific building by ID
  /{building_id}:
    get:
      summary: Get a specific building by ID
      description: Retrieves available building data for specified building
      operationId: GetBuildingById
      tags:
        - Building

      # Define request parameters for this endpoint
      parameters:
        - in: path
          name: building_id
          schema:
            type: string
          description: Building ID
          required: true
          
        - in: header
          name: Authorization
          schema:
            type: string
          description: API Key
          required: true

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Building"
        "401":
          description: API Key provided is not valid.
        "404":
          description: Provided building key is not found.

  # Endpoint to get all buildings
  /buildings:
    get:
      summary: Get All Buildings
      description: Retrieves available building data for all buildings on campus
      operationId: GetAllBuildings
      tags:
        - Building

      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          description: API Key
          required: true

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Building"
        "404":
          description: Invalid

# Define data response objects and properties
components:
  schemas:

    Building:
      type: object
      properties:
        id:
          type: string
          description: Unique ID of building
        name:
          type: string
          format: string
        floors:
          type: array
          items:
            $ref: "#/components/schemas/Floor"
        location:
          $ref: "#/components/schemas/LatLng"
        address:
          type: string
        type:
          type: string
          enum:
            [
            - BuildingTypeUnknown
            - BuildingTypeResidence
            - BuildingTypeDining
            - BuildingTypeOffice
            - BuildingTypeRetail
            - BuildingTypeAcademic
            - BuildingTypeOther
            ]
        id:
          type: string
          description: The unique id of a building

    LatLng:
      type: object
      properties:
        lat:
          type: number
          format: float64
          description: latitude
        lng:
          type: number
          format: float64
          description: longitude
    
    Room:
      type: object
      properties:
        name:
          type: string
        level:
          type: integer
    
    Floor:
      type: object
      properties:
        name:
          type: string
        level:
          type: integer
        rooms:
          type: array
          items:
            $ref: "#/components/schemas/Room"
