---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: api
  namespace: production
spec:
  selector:
    istio: gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - ods.elon.edu
    # - port:
    #     number: 443
    #     name: https
    #     protocol: HTTPS
    #   hosts:
    #     - ods.elon.edu
    #     - api.ods.elon.edu
    #   tls:
    #     credentialName: api-devopsbyexample-com-crt
    #     mode: SIMPLE