---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
  namespace: production
spec:
  hosts:
    - ods.elon.edu
    - frontend
  gateways:
    - gateway
  http:
    - match:
      uri: 
        regex: /saml/*
      route:
        - destination:
            host: backend
            subset: v1
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: frontend
            subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backend
  namespace: production
spec:
  hosts:
    - api.ods.elon.edu
    - backend
  gateways:
    - gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: backend
            subset: v1